import Head from 'next/head'

// Pulling in data from Nasa and ZenQuotes APIs
export const getStaticProps = async () => {
  const nasaRes = await fetch('https://api.nasa.gov/planetary/apod?api_key=4D3DfuIitOHR4LyC1lsQYo70iFPpJ67oDXG4TJw0');
  const nasaData = await nasaRes.json();

  const quotesRes = await fetch('https://zenquotes.io/api/random');
  const quoteData = await quotesRes.json();

  const data = {
    nasaData,
    quoteData
  }

  return {
    props: { allData: data }
  }
}
export default function Home({ allData: { nasaData, quoteData }}) {
  return (
    // Main wrapper with background image
    <main class="flex justify-center items-center w-screen h-screen bg-no-repeat bg-cover bg-center" style={{ backgroundImage: (nasaData.url && nasaData.media_type === 'photo') ? `url('${(nasaData.url)}')` : 'url(/galaxy.jpg)', }}>
      <Head>
        <title>Quote of the Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/quote.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet" />
      </Head>
      {/* Quote wrapper with background */}
        <section class="max-w-md rounded-xl p-10 m-10 bg-gradient-to-t from-black/50 to-black/20 text-white font-serif md:p-16 md:max-w-xl lg:max-w-3xl xl:max-w-5xl">
          <h1 class="text-3xl md:text-4xl">{quoteData[0].q}</h1>
          {quoteData[0].a ? 
          <span class="block text-xl mt-5 md:text-2xl md:mt-7 lg:mt-10">- {quoteData[0].a}</span> 
          :
          /* If there's no known author, revert to Author Unknown */
          <span class="block text-xl mt-5 md:text-2xl md:mt-7 lg:mt-10">- Author Unknown</span>
          }
        </section>
    </main>
  )
}
